# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(010100)
$foreground = rgb(FCF5E7)
$color0 = rgb(010100)
$color1 = rgb(343718)
$color2 = rgb(683B27)
$color3 = rgb(6B3D29)
$color4 = rgb(945F3F)
$color5 = rgb(9B6442)
$color6 = rgb(B8AA8C)
$color7 = rgb(F2E8D4)
$color8 = rgb(A9A295)
$color9 = rgb(454920)
$color10 = rgb(8B4E34)
$color11 = rgb(8F5136)
$color12 = rgb(C67E53)
$color13 = rgb(CE8558)
$color14 = rgb(F6E2BB)
$color15 = rgb(F2E8D4)
