# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000005)
$foreground = rgb(F1ECF2)
$color0 = rgb(000005)
$color1 = rgb(252532)
$color2 = rgb(282834)
$color3 = rgb(534E5C)
$color4 = rgb(56515F)
$color5 = rgb(56515F)
$color6 = rgb(A097A4)
$color7 = rgb(E2DCE5)
$color8 = rgb(9E9AA0)
$color9 = rgb(313142)
$color10 = rgb(353546)
$color11 = rgb(6F687B)
$color12 = rgb(736C7F)
$color13 = rgb(736C7F)
$color14 = rgb(D6C9DB)
$color15 = rgb(E2DCE5)
