# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1C1A23)
$foreground = rgb(FDF2EA)
$color0 = rgb(43404A)
$color1 = rgb(1A1336)
$color2 = rgb(552F4F)
$color3 = rgb(904B68)
$color4 = rgb(984F6B)
$color5 = rgb(357385)
$color6 = rgb(BBA393)
$color7 = rgb(F4E4D9)
$color8 = rgb(AB9F98)
$color9 = rgb(221948)
$color10 = rgb(713F69)
$color11 = rgb(C0648A)
$color12 = rgb(CB698F)
$color13 = rgb(4699B1)
$color14 = rgb(FAD9C4)
$color15 = rgb(F4E4D9)
