# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(332825)
$foreground = rgb(FEF9F0)
$color0 = rgb(594D49)
$color1 = rgb(39140A)
$color2 = rgb(421E13)
$color3 = rgb(6A5042)
$color4 = rgb(A35932)
$color5 = rgb(938270)
$color6 = rgb(BCB39F)
$color7 = rgb(F5EFE1)
$color8 = rgb(ABA79E)
$color9 = rgb(4C1B0D)
$color10 = rgb(57281A)
$color11 = rgb(8E6B58)
$color12 = rgb(D97743)
$color13 = rgb(C4AD96)
$color14 = rgb(FBEFD4)
$color15 = rgb(F5EFE1)
