# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(202026)
$foreground = rgb(F0E6B6)
$color0 = rgb(46464D)
$color1 = rgb(34332B)
$color2 = rgb(4D4023)
$color3 = rgb(615728)
$color4 = rgb(A4293D)
$color5 = rgb(958323)
$color6 = rgb(9E8A22)
$color7 = rgb(E0D38E)
$color8 = rgb(9D9463)
$color9 = rgb(46443A)
$color10 = rgb(67562F)
$color11 = rgb(817535)
$color12 = rgb(DB3752)
$color13 = rgb(C7AE2F)
$color14 = rgb(D3B82E)
$color15 = rgb(E0D38E)
