# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(000005)
$foreground = rgb(F0ECF2)
$color0 = rgb(000005)
$color1 = rgb(252631)
$color2 = rgb(282834)
$color3 = rgb(534E5C)
$color4 = rgb(56515E)
$color5 = rgb(56515E)
$color6 = rgb(A098A4)
$color7 = rgb(E2DCE4)
$color8 = rgb(9E9AA0)
$color9 = rgb(313241)
$color10 = rgb(353645)
$color11 = rgb(6F687A)
$color12 = rgb(736C7E)
$color13 = rgb(736C7E)
$color14 = rgb(D5CADA)
$color15 = rgb(E2DCE4)
