# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

#Applications
exec-once = [workspace 2 silent] discord
exec-once = com.nextcloud.desktopclient.nextcloud --background
exec-once = org.openrgb.OpenRGB --startminimized -p Ice.orp
exec-once = coolercontrol
exec-once = solaar
exec-once = [workspace 3 silent] com.bitwarden.desktop
exec-once = org.localsend.localsend_app --hidden
exec-once = [worspace 9 silent] sudo timeshift --scripted

#Theming
exec-once = hyprctl setcursor Future-cursors 24

#Deamons
exec-once = swww-daemon
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar
exec-once = nm-applet
exec-once = swaync
exec-once = hypridle
exec-once = wl-paste --watch clipvault store

