# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# Ensure the systemd environment is aware of the session
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Force start the graphical-session target
exec-once = systemctl --user start graphical-session.target

# Applications - Clean launch (Rules handle the placement)
exec-once = discord
exec-once = com.nextcloud.desktopclient.nextcloud --background
exec-once = openrgb --startminimized -p Ice.orp
exec-once = coolercontrol
exec-once = solaar --window-hide
exec-once = com.bitwarden.desktop --hidden
exec-once = org.localsend.localsend_app --hidden

#Theming
exec-once = hyprctl setcursor Future-cursors 24

#Deamons
exec-once = awww-daemon --format xrgb &
exec-once = systemctl --user start hyprpolkitagent
exec-once = systemctl --user enable --now hyprpolkitagent.service
exec-once = waybar
exec-once = nm-applet
exec-once = swaync
exec-once = hypridle
exec-once = wl-paste --watch clipvault store
exec-once = arch-update --tray

#Fixes

exec-once = sleep 2 && hyprctl dispatch workspace 1 && hyprctl dispatch focusmonitor DP-1
