hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("WLR_DRM_DEVICES", "/dev/dri/card0")
hl.env("SDL_VIDEO_FULLSCREEN_HEAD", "0")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("GDK_BACKEND", "wayland")
hl.env("PROTON_ENABLE_WAYLAND", "1")

hl.permission({ binary = "/usr/bin/hypr-dock", type = "screencopy", mode = "allow" })
hl.permission({ binary = "/usr/bin/hypr-alttab", type = "screencopy", mode = "allow" })
