-- Generated by nwg-displays on 2026-05-31 at 00:17:39. Do not edit manually.

hl.monitor({
    output = "desc:Samsung Electric Company Odyssey G5 HK2YA00728",
    mode = "2560x1440@164.84",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "desc:Iiyama North America PL2796HS 1179711501071",
    mode = "1920x1080@74.97",
    position = "2560x0",
    scale = 1.0
})
