# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

#Applications
exec-once = vesktop
exec-once = discord
exec-once = com.nextcloud.desktopclient.nextcloud --background
exec-once = openrgb --startminimized -p Ice.orp
exec-once = coolercontrol
#Theming
exec-once = hyprctl setcursor Future-cursors 24

#Deamons
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar 
exec-once = nm-applet 
exec-once = swaync
exec-once = swww-daemon
exec-once = Hypridle
